#!/bin/bash
set -e

CERT_DIR="/etc/apache2/certs"
CERT_FILE="$CERT_DIR/server.crt"
KEY_FILE="$CERT_DIR/server.key"
APACHE_CONF="/etc/apache2/sites-available/000-default.conf"
APP_BASE_URL="${APP_BASE_URL:-https://localhost}"

get_cert_host() {
    local url_host="${APP_BASE_URL#http://}"
    url_host="${url_host#https://}"
    url_host="${url_host%%/*}"

    if [[ "$url_host" == \[*\] ]]; then
        url_host="${url_host#\[}"
        url_host="${url_host%\]}"
    else
        url_host="${url_host%%:*}"
    fi

    if [[ -z "$url_host" ]]; then
        url_host="localhost"
    fi

    printf '%s\n' "$url_host"
}

get_cert_san() {
    local cert_host
    cert_host="$(get_cert_host)"

    if [[ "$cert_host" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || [[ "$cert_host" == *:* ]]; then
        printf 'IP:%s\n' "$cert_host"
    else
        printf 'DNS:%s\n' "$cert_host"
    fi
}

configure_canonical_origin() {
    APP_BASE_URL="${APP_BASE_URL%/}"

    case "$APP_BASE_URL" in
        http://*|https://*) ;;
        *)
            echo "APP_BASE_URL must start with http:// or https://" >&2
            exit 1
            ;;
    esac

    sed -i "s|__APP_BASE_URL__|$APP_BASE_URL|g" "$APACHE_CONF"
}

ensure_tls_certificates() {
    local cert_host
    local cert_san
    local current_cn
    local current_issuer_cn

    cert_host="$(get_cert_host)"
    cert_san="$(get_cert_san)"

    if [[ -s "$CERT_FILE" && -s "$KEY_FILE" ]]; then
        current_cn="$(openssl x509 -in "$CERT_FILE" -noout -subject 2>/dev/null | sed -n 's/.*CN *= *//p' | head -n 1)"
        current_issuer_cn="$(openssl x509 -in "$CERT_FILE" -noout -issuer 2>/dev/null | sed -n 's/.*CN *= *//p' | head -n 1)"

        if [[ "$current_cn" == "$cert_host" ]]; then
            return
        fi

        if [[ "$current_cn" != "localhost" || "$current_issuer_cn" != "$current_cn" ]]; then
            return
        fi

        echo "Existing autogenerated localhost certificate does not match APP_BASE_URL host. Regenerating self-signed certificate..."
        rm -f "$CERT_FILE" "$KEY_FILE"
    fi

    echo "TLS certificate files not found. Generating self-signed development certificate..."

    if [[ ! -w "$CERT_DIR" ]]; then
        CERT_DIR="/tmp/certs"
        CERT_FILE="$CERT_DIR/server.crt"
        KEY_FILE="$CERT_DIR/server.key"
        mkdir -p "$CERT_DIR"

        sed -i "s|^\s*SSLCertificateFile\s\+.*$|    SSLCertificateFile $CERT_FILE|" "$APACHE_CONF"
        sed -i "s|^\s*SSLCertificateKeyFile\s\+.*$|    SSLCertificateKeyFile $KEY_FILE|" "$APACHE_CONF"
    else
        mkdir -p "$CERT_DIR"
    fi

    openssl req -x509 -nodes -newkey rsa:2048 \
        -keyout "$KEY_FILE" \
        -out "$CERT_FILE" \
        -days 365 \
        -subj "/CN=$cert_host" \
        -addext "subjectAltName=$cert_san" >/dev/null 2>&1
}

echo "=== TransactiWar Setup ==="
configure_canonical_origin
ensure_tls_certificates
echo "Waiting for MySQL to be ready..."

until mysqladmin ping -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" --skip-ssl --silent 2>/dev/null; do
    echo "  MySQL not ready, retrying in 2s..."
    sleep 2
done

echo "MySQL is ready."

# Create test accounts
echo "Creating test accounts..."
/create_accounts.sh

apache2ctl -t

echo "Setup complete. Starting Apache..."
exec apache2-foreground
